server:
  port: 3333
#指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
spring:
  profiles:
    active: swagger
  application:
    name: feign-consumer
eureka:
  instance:
    prefer-ip-address: true
  client:
    eureka-service-url-poll-interval-seconds: 1
    service-url:
      defaultZone: http://localhost:1110/eureka/,http://svr1:1111/eureka/,http://svr2:1112/eureka/
debug: true