#相当于服务的ID,以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: service-hi
server:
  port: 8762
eureka:
  client:
    service-url:
        defaultZone: http://localhost:1110/eureka/,http://svr1:1111/eureka/,http://svr2:1112/eureka/