eureka:
  client:
    service-url:
        defaultZone: http://localhost:1110/eureka/,http://svr1:1111/eureka/,http://svr2:1112/eureka/
spring:
  application:
    name: service-zuul
server:
  port: 8711

#router config
zuul:
  routes:
     api-ribbon:
       path: /api-ribbon/**
       serviceId: api-ribbon
     api-feign:
       path: /api-feign/**
       serviceId: api-feign
  ribbon-isolation-strategy: thread
logging:
  level: debug


